arb-dir: assets/intl
template-arb-file: intl_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/l10n
preferred-supported-locales: [en, es]
use-deferred-loading: false
synthetic-package: false
